apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bkapmy67u-go 
  janus-idp.io/tekton: bkapmy67u-go
  backstage.io/kubernetes-id: bkapmy67u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bkapmy67u-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  