apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bkapmy67u-go-gitops
  description: This is GitOps manifest for bkapmy67u-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bkapmy67u-go
    backstage.io/kubernetes-id: bkapmy67u-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: bkapmy67u-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bkapmy67u-go
